"""empty message

Revision ID: 482dc05a1808
Revises: d034b2213274
Create Date: 2018-07-11 19:01:57.124446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482dc05a1808'
down_revision = 'd034b2213274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
