"""empty message

Revision ID: 60bda783b21f
Revises: d38c01629236
Create Date: 2018-07-30 12:33:09.270669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bda783b21f'
down_revision = 'd38c01629236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image')
    # ### end Alembic commands ###
